# Generated by Django 3.1.1 on 2020-09-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200910_0136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exhbit_data',
            new_name='Exhibit_data',
        ),
    ]
