# Generated by Django 3.1.1 on 2020-09-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200910_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=50, null=True)),
                ('contact_email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='exhibit_data',
            name='description',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibit_data',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='exhibit_data',
            name='startdate',
            field=models.DateField(null=True),
        ),
    ]
