# Generated by Django 3.1.1 on 2020-09-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200911_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution_data',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
