# Generated by Django 3.1.1 on 2020-09-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_institution_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit_data',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
