# Generated by Django 3.1.1 on 2020-09-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200912_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exhibit_data',
            old_name='author',
            new_name='author_exhibit',
        ),
        migrations.RenameField(
            model_name='exhibit_data',
            old_name='description',
            new_name='description_exhibit',
        ),
        migrations.RenameField(
            model_name='exhibit_data',
            old_name='enddate',
            new_name='enddate_exhibit',
        ),
        migrations.RenameField(
            model_name='exhibit_data',
            old_name='name',
            new_name='name_exhibit',
        ),
        migrations.RenameField(
            model_name='exhibit_data',
            old_name='startdate',
            new_name='startdate_exhibit',
        ),
        migrations.RenameField(
            model_name='exhibit_data',
            old_name='url',
            new_name='url_exhibit',
        ),
        migrations.RenameField(
            model_name='institution_data',
            old_name='address',
            new_name='address_institution',
        ),
        migrations.RenameField(
            model_name='institution_data',
            old_name='name',
            new_name='category_institution',
        ),
        migrations.RenameField(
            model_name='institution_data',
            old_name='contact_email',
            new_name='contact_email_institution',
        ),
        migrations.RenameField(
            model_name='institution_data',
            old_name='contact_phone',
            new_name='contact_phone_institution',
        ),
        migrations.RenameField(
            model_name='institution_data',
            old_name='category',
            new_name='name_institution',
        ),
    ]
