# Generated by Django 3.1.1 on 2020-09-12 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200912_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution_data',
            old_name='url',
            new_name='url_institution',
        ),
    ]
