# Generated by Django 3.1.1 on 2020-09-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200912_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit_data',
            name='description_exhibit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exhibit_data',
            name='enddate_exhibit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exhibit_data',
            name='startdate_exhibit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
