# Generated by Django 3.1.1 on 2020-09-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200910_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhbit_data',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exhbit_data',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='exhbit_data',
            name='startdate',
        ),
        migrations.AddField(
            model_name='exhbit_data',
            name='author',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exhbit_data',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
